[workspace]
members = [
  ".",
  "openapi",
  "bench/binary_size"
]

[package]
name = "async-stripe"
version = "0.14.0"
description = "API bindings for the Stripe HTTP API"
rust-version = "1.54.0"
authors = [
  "Anna Baldwin <abaldwin@developers.wyyerd.com>",
  "Kevin Stenerson <kestred@users.noreply.github.com>",
  "Alexander Lyon <arlyon@me.com>",
]
license = "MIT OR Apache-2.0"
readme = "README.md"
homepage = "https://github.com/arlyon/async-stripe"
repository = "https://github.com/arlyon/async-stripe"
documentation = "https://docs.rs/async-stripe"
keywords = ["stripe", "v1", "api", "async"]
categories = ["api-bindings"]
edition = "2018"
resolver = "2"

[package.metadata.docs.rs]
features = ["runtime-tokio-hyper"]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples=examples"]

[lib]
name = "stripe"
crate-type = ["cdylib", "rlib"]

[features]
default = ["full", "webhook-events", "uuid"]
full = [
  "checkout",
  "billing",
  "connect",
  "fraud",
  "issuing",
  "orders",
  "sigma",
  "webhook-endpoints",
]

# wasm = ["getrandom/js"]

# stripe feature groups
checkout = ["billing"]
billing = []
connect = []
fraud = []
issuing = []
orders = []
sigma = []
webhook-endpoints = []

# deserialize events from webhooks
webhook-events = ["events", "hmac", "sha2", "chrono", "hex"]
events = []

# runtimes
async = []
blocking = []

runtime-wasm = ["runtime-tokio-reqwest", "getrandom/js"]
runtime-tokio-reqwest = ["tokio", "async", "reqwest"]

runtime-tokio-hyper = ["tokio", "hyper-client", "hyper-tls", "async"]
runtime-tokio-hyper-rustls = ["tokio", "hyper-client", "hyper-rustls", "async"]
runtime-blocking = ["tokio", "tokio/rt", "hyper-client", "hyper-tls", "blocking"]
runtime-blocking-rustls = [
  "tokio",
  "tokio/rt",
  "hyper-client",
  "hyper-rustls",
  "blocking",
]
runtime-async-std-surf = ["async-std", "surf", "async"]

# we need the compat crate if using hyper
hyper-client = ["hyper", "http-types/hyperium_http"]

[dependencies]
async-std = { version = "1.9", optional = true }
chrono = { version = "0.4", features = ["serde"], optional = true }
thiserror = "1.0.24"
http-types = "2.12.0"
hyper = { version = "0.14", default-features = false, features = ["http1", "http2", "client", "tcp"], optional = true }
hyper-tls = { version = "0.5", optional = true }
hyper-rustls = { version = "0.22", optional = true }
reqwest = {version="0.11", optional=true}
serde = ">=1.0.79" # we use `serde(other)` which was introduced in 1.0.79
serde_path_to_error = "^0.1.5"
serde_derive = ">=1.0.79"
serde_json = "1.0"
serde_qs = "0.8"
smol_str = "0.1"
surf = { version = "2.1", optional = true }
tokio = { version = "1.2", optional = true }
smart-default = "0.6.0"
uuid = { version = "0.8", optional=true, features=["v4"] }

# webhook support
hmac = { version = "0.12", optional = true }
sha2 = { version = "0.10", optional = true }
hex = { version = "0.4", optional = true }

# wasm
getrandom = "0.2"

[dev-dependencies]
anyhow = "1.0.38"
async-std = { version = "1.10.0", features = ["attributes"] }
httpmock = "0.6.6"
lazy_static = "1.4"
tokio = { version = "1.2", features = ["rt", "macros"] }
axum = "0.4.8"
actix-web = "4.0.1"

[patch.crates-io]
http-types = { git = "https://github.com/arlyon/http-types.git", branch = "backports/rand" }

[[example]]
name = "checkout"
required-features = ["runtime-tokio-hyper"]

[[example]]
name = "connect"
required-features = ["runtime-tokio-hyper"]

[[example]]
name = "customer"
required-features = ["runtime-tokio-hyper"]

[[example]]
name = "payment-intent"
required-features = ["runtime-tokio-hyper"]

[[example]]
name = "payment-link"
required-features = ["runtime-tokio-hyper"]

[[example]]
name = "subscriptions"
required-features = ["runtime-tokio-hyper"]

[[example]]
name = "webhook-axum"
required-features = ["runtime-tokio-hyper"]

[[example]]
name = "webhook-actix"
required-features = ["runtime-tokio-hyper"]
